
# Время до смены стадии, после вызова команды
timer: 10

# Радиус вокруг центра платформы, в котором будут уведомлены люди о смене платформы
radius_notice: 100

# Количество платформ на одной странице при вызове команды /stp list
amount_platform_on_list: 8



platforms:
# Пример создания платформв:
#
# [name_platform] - Название платформы
#   center_point: [position] - Координаты центра платформы (Шаблон: [world] [X] [Y] [Z])
#   general_schematic: [name_schematic] - Название схематики из плагина WorldEdit, основной стадии (/stp paste *)
#   stages:
#     [name_stage]: [name_schematic] - Название стадии и название схематики, вставляющаяся при переходе к этой стадии (количество стадии может быть любым)
#

  sumo_ice:
    center_point: world 1069 0 -653
    general_schematic: "sumoL_stage0"
    stages:
      big: "sumoL_stage1"
      medium: "sumoL_stage2"
      small: "sumoL_stage3"
  sumo_classic:
    center_point: world 1069 0 -653
    general_schematic: "sumoCL_stage0"
    stages:
      orange: "sumoCL_stage1"
      yellow: "sumoCL_stage2"
      green: "sumoCL_stage3"

